### ISSUE TITLE
Not reading other compendiums 

### ISSUE THREAD

**Issue by hedgehog8711** [HeroCreationLab/hero-creation-tool#126] opened 2022-09-30 15:02 UTC
I noticed that when I had the item null, that I only had the DDB item folder selected. I added the Core Items folder and that allowed the tool to load without issue. It seems that when ever something other than the core content the tool cant find it. Here is all the information that I could find. The issue continues even it the Hero Creation tool is the only Active module. 

Foundry Virtual Tabletop: Version 10, 10.286
Game System: dnd5e, 2.0.3
Hero Creation tool 1.9.0
Active Modules: 141
Performance Mode: 2

Actors: 21 | Items: 13 | Journal: 50 | Rollable Tables: 0 |
Playlists: 1 | Compendium Packs: 116 | Chat Messages: 1

error from console
![error](https://user-images.githubusercontent.com/114251484/193298229-4ccd8b57-d658-42dc-9fcd-0cc017791317.PNG)

With another compendium selected 
![DDB races selected](https://user-images.githubusercontent.com/114251484/193298468-bd66750e-716e-4339-8e36-7aeb12524a14.PNG)

using just the core compendium
![unselected ddb races](https://user-images.githubusercontent.com/114251484/193298597-604fa843-3844-4bf7-b1a8-ad512fff39b2.PNG)

**Comment by ccjmk** [comment] 2023-01-08 18:29
Hi @hedgehog8711 ! sorry for the longest delay, I was in the middle of moving to a new country so.. lots of things had to happen before I could get back at this heheh

I just made a quick test both with default compendiums and compendiums imported from DDBImporter, and it seems to work. Could you try reimporting the compendiums? It seems to be caused by a change in the data structure of race items; Before, the field would be [item].data.data.requirements IIRC, now it's [item].system.requirements, so you might be using Race items imported before that change.

**Comment by hedgehog8711** [comment] 2023-01-09 15:30
No problem thanks for taking the time to look at it and yes it seems like it might have been something the the DnD import tool that I was using after a couple of updates everything started working. Thank you again for taking the time and I hope that you get settled well, and thanks for making such a great tool.
ThanksGreg
    On Sunday, January 8, 2023 at 01:29:26 PM EST, ccjmk ***@***.***> wrote:  
 
 


Hi @hedgehog8711 ! sorry for the longest delay, I was in the middle of moving to a new country so.. lots of things had to happen before I could get back at this heheh

I just made a quick test both with default compendiums and compendiums imported from DDBImporter, and it seems to work. Could you try reimporting the compendiums? It seems to be caused by a change in the data structure of race items; Before, the field would be [item].data.data.requirements IIRC, now it's [item].system.requirements, so you might be using Race items imported before that change.

**Comment by ccjmk** [comment] 2023-01-09 15:50
I'm very happy! sometimes these issues are a little hard to review, so I like it this was relatively easy. Thanks for the kind words! :)

**Closed by ccjmk** 2023-01-09 15:50 UTC
Labels: waiting feedback
