### ISSUE TITLE
Races not sorted by the correct prerequisite if there is a "-" in the name

### ISSUE THREAD

**Issue by MaxPat931** [HeroCreationLab/hero-creation-tool#35] opened 2021-08-28 23:53 UTC
All my Half-Elf races are being listed under the Elf, even though the prerequisite is set to Half-Elf

![image](https://user-images.githubusercontent.com/86370342/131233767-f13570de-e85f-4fa9-b037-a898145a2c79.png)

**Comment by ccjmk** [comment] 2021-08-29 14:14
@MaxPat931 version 1.1.3 should fix this, at least according to my testing! Let me know how it works for you, in case I needed to fix something else i missed.

**Comment by MaxPat931** [comment] 2021-08-29 18:13
This did fix the above issue, but it also changed the behavior for multiple instances of the same race.
Because the Parent Race cannot be selected when there are subraces available, I would have 2 instances of a Parent race if it should be a playable option. Previously, the module would only place the subraces under one version, and the other would be treated as a separate race.

1.1.2
![image](https://user-images.githubusercontent.com/86370342/131260284-7a63466c-f2a8-4a1f-9d13-8a8327c8f0ed.png)

But now, the subraces are listed under both instances of the Parent Race
1.1.3
![image](https://user-images.githubusercontent.com/86370342/131260915-56a9fe59-2c92-4d09-9ccf-b90cd36490ef.png)

This applies to Half-Elf, Half-Orc, Human, and Tiefling (from my DDB resources)

**Comment by ccjmk** [comment] 2021-09-01 10:34
@MaxPat931 im a little torn on this one. I consider that not been able to select the parent race is "expected behaviour". You can't be a "Dwarf" without been a mountain/hill/etc dwarf, for example. There just isn't a "not-subrace" dwarf. Same for other races. Variant races do pose a problem to this though, but I think the best solution is to create a "Vanilla" or default race.

For example, in the case of Humans from your screenshot, I think like just like you have all the Mark of * and Variant Human, there should be an extra one as "Default" or just.. Human maybe. But technically speaking, that would be a "Human" subclass. 

That said, I think that the expected behaviour here would be either not showing any consecutive repeated race I find while iterating through the parent races list (so the whole second Human... would be ignored - but this would probably cause some usability issues where people have a repeated race not realizing it, and the module picks the one they don't want without them realizing), or simply leaving everything as-is, and if you repeat a race, you see them repeated (an error, but an easier error to see for the user)

As far as I understand from DDBImporter, each of their races have the whole content of both parent race and subrace, so the parent race is "not needed" but its actually required by this module to order stuff. What could probably work is just copying the SRD human race into a custom races compendium on your world, create an empty "Human" base race, and set the SRD copied race to be a subrace of that. That way, you can pick the "default" human as a subclass of human, and the DDBImporter ones will also be appropriately ordered while not adding anything undesired.

DO NOTE that this will probably change once [dnd5e system implements Race items](https://gitlab.com/foundrynet/dnd5e/-/issues/342), because there both my module and DDBImporter will probably be able to do a better job keeping these things ordered.

**Comment by ccjmk** [comment] 2021-09-01 19:38
MrPrimate is aware of some odd interactions with my module, so we can probably work something out; its just a matter of thinking ahead and seeing where's the easiest and most reasonable change, if making an exception here or there.

The second one should definitely be another ticket, it was something I had in mind already but please feel free to make the ticket so we can keep track of it!

**Comment by ccjmk** [comment] 2021-09-01 19:39
So, after our conversation, i gather that this is no longer an ongoing bug, closing this ticket!

**Closed by ccjmk** 2021-09-01 19:39 UTC
Labels: bug

**Comment by MaxPat931** [comment] 2021-09-01 19:42
I think the only thing unresolved is the matching subraces from different compendiums, having both listings point to the same record. But could be chalked up to improper setup I guess.
